### ISSUE TITLE
Unknown control type: backendmaps

### ISSUE THREAD

**Issue by Neolot** [adc91/backend-google-maps#3]
Hello!
I installed the plugin and added a control to backend form, but it does not work:
Unknown control type: backendmaps
October CMS Release: 443
Can you help with it?

**Comment by adc91** [comment]
Hello,

Are you using the Rainlab Builder?

If so, do not worry, it should appear on your form when your controller is defined since it is compatible with the latest version.

Only the official widgets will appear in the Builder.

**Comment by Neolot** [comment]
Yes, I'm using Rainlab Builder)
Ok, I understand.
Thanks of your help, Angel!
